import {Injectable} from '@angular/core'
import {HttpClient, HttpParams} from '@angular/common/http'
import {Observable} from 'rxjs'
import {IIncoming} from '../components/sortirovka/interfaces/invoices.interface'
import {AppService} from '../../../shared/services/app.service'

@Injectable({
  providedIn: 'root',
})
export class SortingService {
  apiUrl: string = ''

  constructor(private http: HttpClient, private appService: AppService) {
    this.apiUrl = appService.urlApiPdp
  }

  getIncomingInvoices(
    region: number,
    invoiceDate: string
  ): Observable<IIncoming[]> {
    const params = new HttpParams({
      fromObject: {region: region, data: invoiceDate},
    })
    return this.http.get<IIncoming[]>(`${this.apiUrl}prihod`, {params: params})
  }

  // getPrihod(region: number, invoiceDate: string): IIncoming[] {
  //   return [
  //     {
  //       id_rec: 768448,
  //       barcode: '9771818336223',
  //       indizd: '00196',
  //       naimen:
  //         'Экономический бюллетень научно-исследовательского экономического института Министерства экономики Республики Беларусь',
  //       nom_izd: '9',
  //       nom_count: 6,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768449,
  //       barcode: '9772518194007',
  //       indizd: '00361',
  //       naimen: 'УМНЯША',
  //       nom_izd: '9',
  //       nom_count: 8,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768450,
  //       barcode: '9772220299007',
  //       indizd: '00480',
  //       naimen: 'Секретарское дело',
  //       nom_izd: '9',
  //       nom_count: 5,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768451,
  //       barcode: '9771998929000',
  //       indizd: '00583',
  //       naimen: 'Налоги Беларуси',
  //       nom_izd: '36',
  //       nom_count: 135,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768452,
  //       barcode: null,
  //       indizd: '00598',
  //       naimen: 'Законность и правопорядок',
  //       nom_izd: '3',
  //       nom_count: 152,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768453,
  //       barcode: null,
  //       indizd: '00651',
  //       naimen: 'Белорусское сельское хозяйство',
  //       nom_izd: '9',
  //       nom_count: 12,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768454,
  //       barcode: null,
  //       indizd: '00787',
  //       naimen: 'Доклады БГУИР',
  //       nom_izd: '6',
  //       nom_count: 1,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768455,
  //       barcode: '9771819383004',
  //       indizd: '01008',
  //       naimen: 'Журнал специального назначения',
  //       nom_izd: '5',
  //       nom_count: 6,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768456,
  //       barcode: '9772077978001',
  //       indizd: '01323',
  //       naimen: 'Кем быть?',
  //       nom_izd: '9',
  //       nom_count: 3,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768457,
  //       barcode: '4607038590693',
  //       indizd: '12777',
  //       naimen: 'Загадки истории',
  //       nom_izd: '40',
  //       nom_count: 11,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768458,
  //       barcode: '4680002710549',
  //       indizd: '14005',
  //       naimen: 'Магические истории',
  //       nom_izd: '10',
  //       nom_count: 3,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768459,
  //       barcode: '4640018900303',
  //       indizd: '14019',
  //       naimen: 'Бабушкин пирог. Кейворды',
  //       nom_izd: '40',
  //       nom_count: 1,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768460,
  //       barcode: '4640018900150',
  //       indizd: '14021',
  //       naimen: 'Бабушкин пирог',
  //       nom_izd: '10',
  //       nom_count: 1,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768461,
  //       barcode: '4640018900334',
  //       indizd: '14049',
  //       naimen: 'Бабушкин пирог. Филворды',
  //       nom_izd: '40',
  //       nom_count: 1,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768462,
  //       barcode: '4640018900242',
  //       indizd: '14056',
  //       naimen: 'Дарья. Ключворд',
  //       nom_izd: '40',
  //       nom_count: 1,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768463,
  //       barcode: '4640018900655',
  //       indizd: '14077',
  //       naimen: 'Дарья. Филворд',
  //       nom_izd: '40',
  //       nom_count: 1,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768464,
  //       barcode: '4680002710099',
  //       indizd: '16820',
  //       naimen: 'Магия и красота',
  //       nom_izd: '20',
  //       nom_count: 7,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768465,
  //       barcode: '4607038590792',
  //       indizd: '44443',
  //       naimen: 'Невыдуманные истории',
  //       nom_izd: '40',
  //       nom_count: 13,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768466,
  //       barcode: '4607038591447',
  //       indizd: '44446',
  //       naimen: 'Тайны СССР',
  //       nom_izd: '20',
  //       nom_count: 14,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768467,
  //       barcode: '4607038591140',
  //       indizd: '49100',
  //       naimen: 'Ёжик',
  //       nom_izd: '10',
  //       nom_count: 22,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768468,
  //       barcode: '9770233427776',
  //       indizd: '50102',
  //       naimen: 'Правда',
  //       nom_izd: '108',
  //       nom_count: 2,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768469,
  //       barcode: null,
  //       indizd: '63241',
  //       naimen: 'Транспортная безопасность',
  //       nom_izd: '37',
  //       nom_count: 29,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768470,
  //       barcode: '9771993123007',
  //       indizd: '63318',
  //       naimen: 'Мир косметики Белита-Витэкс',
  //       nom_izd: '9',
  //       nom_count: 824,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768471,
  //       barcode: null,
  //       indizd: '63547',
  //       naimen: 'Энергетика Беларуси',
  //       nom_izd: '18',
  //       nom_count: 3,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768472,
  //       barcode: '9771990763008',
  //       indizd: '63850',
  //       naimen: 'Звязда',
  //       nom_izd: '193',
  //       nom_count: 103,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768473,
  //       barcode: '9771993133006',
  //       indizd: '63869',
  //       naimen: 'Белорусская военная газета. Во славу Родины',
  //       nom_izd: '113',
  //       nom_count: 226,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768474,
  //       barcode: '9771994478007',
  //       indizd: '63875',
  //       naimen: 'Культура',
  //       nom_izd: '40',
  //       nom_count: 36,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768475,
  //       barcode: '9771991532009',
  //       indizd: '63884',
  //       naimen: 'Рэспублiка',
  //       nom_izd: '188',
  //       nom_count: 190,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768476,
  //       barcode: '9771992305008',
  //       indizd: '63889',
  //       naimen: 'СБ. Беларусь сегодня',
  //       nom_izd: '193',
  //       nom_count: 1938,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768477,
  //       barcode: '9772411574005',
  //       indizd: '63911',
  //       naimen: 'Живая вода',
  //       nom_izd: '40',
  //       nom_count: 24,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768478,
  //       barcode: '9771993057005',
  //       indizd: '64117',
  //       naimen: 'Железнодорожник Белоруссии',
  //       nom_izd: '75',
  //       nom_count: 171,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768479,
  //       barcode: null,
  //       indizd: '64207',
  //       naimen: 'Домой!',
  //       nom_izd: '9',
  //       nom_count: 8,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768480,
  //       barcode: '9771990930004',
  //       indizd: '64289',
  //       naimen: 'Сельская газета',
  //       nom_izd: '114',
  //       nom_count: 72,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768481,
  //       barcode: '9772409949006',
  //       indizd: '67060',
  //       naimen: 'Шахцер  Солигорский р-н',
  //       nom_izd: '39',
  //       nom_count: 1,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768482,
  //       barcode: null,
  //       indizd: '67066',
  //       naimen: "Iнфa-Kур'ер  Слуцкий р-н",
  //       nom_izd: '39',
  //       nom_count: 1,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768483,
  //       barcode: null,
  //       indizd: '67070',
  //       naimen: 'Новости БелАЗА  г.Жодино',
  //       nom_izd: '39',
  //       nom_count: 1,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768484,
  //       barcode: null,
  //       indizd: '74806',
  //       naimen: 'Весцi БДПУ. Серыя 1. Педагогiка. Псiхалогiя. Фiлалогiя',
  //       nom_izd: '3',
  //       nom_count: 1,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768485,
  //       barcode: null,
  //       indizd: '74816',
  //       naimen:
  //         'Весцi БДПУ. Серыя 2. Гiсторыя. Фiласофiя. Палiталогiя. Сацыялогiя. Эканомiка. Культуралогiя',
  //       nom_izd: '3',
  //       nom_count: 1,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768486,
  //       barcode: null,
  //       indizd: '74819',
  //       naimen:
  //         'Бюллетень Министерства труда и социальной защиты Республики Беларусь',
  //       nom_izd: '9',
  //       nom_count: 14,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768487,
  //       barcode: null,
  //       indizd: '74832',
  //       naimen:
  //         'Весцi БДПУ. Серыя 3. Фiзiка. Матэматыка. Iнфарматыка. Бiялогiя. Геаграфiя',
  //       nom_izd: '3',
  //       nom_count: 1,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768488,
  //       barcode: '9772518702097',
  //       indizd: '74871',
  //       naimen: 'КОГДА ТЫ ОДИН ДОМА',
  //       nom_izd: '9',
  //       nom_count: 16,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768489,
  //       barcode: '9772518701038',
  //       indizd: '74939',
  //       naimen: 'РАЗВЛЕКАТЕЛЬНЫЙ КАЛАМБУР',
  //       nom_izd: '9',
  //       nom_count: 9,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768490,
  //       barcode: '9770131230003',
  //       indizd: '74957',
  //       naimen: 'Маладосць',
  //       nom_izd: '9',
  //       nom_count: 6,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768491,
  //       barcode: '9772071371006',
  //       indizd: '75026',
  //       naimen: 'Проблемы управления',
  //       nom_izd: '3',
  //       nom_count: 11,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768492,
  //       barcode: null,
  //       indizd: '75038',
  //       naimen: 'Современная стоматология',
  //       nom_izd: '3',
  //       nom_count: 1,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768493,
  //       barcode: '4811819526003',
  //       indizd: '75088',
  //       naimen: 'Вестник Белнефтехима',
  //       nom_izd: '9',
  //       nom_count: 242,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768494,
  //       barcode: null,
  //       indizd: '75099',
  //       naimen: 'Энергоэффективность',
  //       nom_izd: '9',
  //       nom_count: 20,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768495,
  //       barcode: '4607038590587',
  //       indizd: '79817',
  //       naimen: 'Моя прекрасная дача',
  //       nom_izd: '20',
  //       nom_count: 25,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768496,
  //       barcode: null,
  //       indizd: '80904',
  //       naimen: 'ЧЕМ РАЗВЛЕЧЬ ГОСТЕЙ',
  //       nom_izd: '9',
  //       nom_count: 1,
  //       magazine: 1,
  //     },
  //     {
  //       id_rec: 768497,
  //       barcode: '4607038590471',
  //       indizd: '99101',
  //       naimen: 'Дарья',
  //       nom_izd: '20',
  //       nom_count: 6,
  //       magazine: 0,
  //     },
  //     {
  //       id_rec: 768498,
  //       barcode: '4607038590020',
  //       indizd: '99382',
  //       naimen: 'Тайны ХХ века',
  //       nom_izd: '40',
  //       nom_count: 20,
  //       magazine: 0,
  //     },
  //   ]
  // }
}
